### ISSUE TITLE
Add support for garages

### ISSUE THREAD

**Issue by paul35621** [gtasa-savegame-editor/gtasa-savegame-editor#11]
[documentation 1 (sadoc)](http://www.paulinternet.nl/sadoc/index.php?page=block03)
[documentation 2 (gtamodding, down)](http://www.gtamodding.com/wiki/Saves_(GTA_SA)#Block_3:_Garages)

**Comment by lfuelling** [comment]
More Helpful links:
- [Garage Format Specification (wikia)](http://gta.wikia.com/wiki/GRGE)
- [Garage (wikia)](http://gta.wikia.com/wiki/Garage)
    - [Garage id's (hashlink)](http://gta.wikia.com/wiki/Garage#San_Andreas)
    - [Garage Names & Positions (hashlink)](http://gta.wikia.com/wiki/Garage#San_Andreas_2)

@paul35621 could you provide the source for `/sadoc` on your website so we can add what we found out? 🙂

**Comment by lfuelling** [comment]
Closing this, since initial support for garages is available.
