### ISSUE TITLE
NullPointerException on Windows

### ISSUE THREAD

**Issue by natediddly** [gtasa-savegame-editor/gtasa-savegame-editor#120]
I'm sorry for asking such a basic question but I can't get the program to work at all. I had no problem using the old 32 bit version of this program from a couple years ago.

I tried downloading and the .jar and the .exe but they both gave the same error:
![savegame error](https://user-images.githubusercontent.com/97095231/148049268-4c9cfe8a-8bc8-4d15-9808-bfea8f5d59b3.png)

I don't really understand the instructions as this is far beyond my competency with computers and I would just like to edit my savegame folder with the same ease as with the 2013-14 version of the program, it was much more user-friendly.

**Comment by umustbeloggedintododat** [comment]
got this issue too, the release version just doesn't work for me and the gtagarage version has this

**Comment by lfuelling** [comment]
@umustbeloggedintododat could you please provide a link to the gtagarage version? 
I have not uploaded any builds of this version on any other sites than GitHub, the [releases page](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases) is the only supported download location.

**Comment by lfuelling** [comment]
@natediddly Reporting this was the correct action to take, thansk for reporting :)

The bug is fixed in [v3.3-rc.23](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/releases/tag/v3.3-rc.23).

**Comment by umustbeloggedintododat** [comment]
https://www.gtagarage.com/mods/show.php?id=28834

**Comment by lfuelling** [comment]
> Last Updated: 25 Mar 2018
 
 😂
