### ISSUE TITLE
Application is unable to detect JRE

### ISSUE THREAD

**Issue by umustbeloggedintododat** [gtasa-savegame-editor/gtasa-savegame-editor#124]
broken

**Comment by lfuelling** [comment]
In case you installed the suggested JDK and use Windows, you must make sure to set the "Set JAVA_HOME" and "Set Oracle Registry Keys" during the installation to make the application able to find the local JRE.

**Comment by lfuelling** [comment]
Closed due to inactivity. 
If this issue is still present, please comment.
