### ISSUE TITLE
Theme resets after reopening

### ISSUE THREAD

**Issue by ErickDiniz** [gtasa-savegame-editor/gtasa-savegame-editor#142]
When I go to put a theme it applies normal, but it doesn't let me click on "Apply" to apply the changes I made and when I reopen the editor, it doesn't have the theme I put, even if I put the theme, change some configuration to release the Apply button, it doesn't save, and if I press the apply button the editor is all white

**Comment by lfuelling** [comment]
Hi, thanks for reporting this. Which operating system are you using?

**Comment by ErickDiniz** [comment]
Windowns

**Comment by ErickDiniz** [comment]
> Hi, thanks for reporting this. Which operating system are you using?

Windows and the last version of the editor
