### ISSUE TITLE
Trojan virus found

### ISSUE THREAD

**Issue by cody151** [gtasa-savegame-editor/gtasa-savegame-editor#192]
https://www.virustotal.com/gui/file/7cfeeaef300793c03a54612ae648c23e4dc751237cf146637efcb44ba136ba58/behavior

**Comment by lfuelling** [comment]
Hi,
thanks for reporting this, but you can see by the finding descriptions that this is intended behavior:

- That "Rising" Scanners match: `Trojan.Generic@AI.86 (RDML:qa6rh/NG4BN/gKY/Ujk3yg)`
    - Seems to be some AI stuff getting triggered by the windows executable wrapper for the java application
- Those two "Sigma Rule" matches:
    - "Potential Defense Evasion Via Binary Rename"
        - This is most likely the update function or savegame handling
    - "File Download From Browser Process Via Inline Link"
        -  Again could be the updater, or any link to github or websites

If you don't want to use the Windows executable, you can also download the `.jar` file from the release page and launch that using your installed Java Runtime.
