### ISSUE TITLE
How to use Zones tab?

### ISSUE THREAD

**Issue by rain1** [gtasa-savegame-editor/gtasa-savegame-editor#193]
How to use Zones editor?

Fields are grayed out.
![image](https://github.com/gtasa-savegame-editor/gtasa-savegame-editor/assets/1515714/29d07be4-4017-4af9-869f-c1b5594e91c0)

Am I missing something or is it not implemented yet? I want to mark all gang zones owned by Groove Street so that I don't have to start a gang war in every zone. But when I select zones, everything seems to be grayed out.

**Comment by lfuelling** [comment]
Hi, the Zones Tab is unfortunately broken at this time. 

See #97 for the current progress and future updates!
