### ISSUE TITLE
Write the config file respecting the XDG Base Directory Specification

### ISSUE THREAD

**Issue by guihkx** [gtasa-savegame-editor/gtasa-savegame-editor#52]
Hey there.

In simple terms, the XDG Base Directory Specification exists to prevent cluttering an user's home directory with dotfiles. The full spec. is here: https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

Currently, GTA:SA Savegame Editor writes its settings file to a hard-coded path: `~/.gta_sa_savegame_editor`.

It would be preferable if it wrote to `$XDG_CONFIG_HOME/gta_sa_savegame_editor`, or maybe `$XDG_CONFIG_HOME/gta_sa_savegame_editor/config`.

Looking up the settings file would look like this (roughly):

1. Check if `~/.gta_sa_savegame_editor` exists, so we don't break backwards compatibility.
2. If it does exist, keep using that path.
3. If it doesn't, check if `$XDG_CONFIG_HOME` is set and use it.
4. Otherwise, fallback to `~/.config/`

Let me know what you think.
Thank you very much!

**Comment by lfuelling** [comment]
Hi, thanks for the suggestion! 
I think it's a great idea, although I'd rather move the old config to the new directory if it exists.
